#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
    uctags --tag-relative=yes -L - -f"$dir/$$.tags" --languages=-sql
mv "$dir/$$.tags" "$dir/tags"
